name: Test Groq Summarization Action
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  test-summarization:
    runs-on: ubuntu-latest
    steps:
      - name: Summarize Content
        # uses: CaiJingLong/action-groq@main
        uses: ./
        id: summary
        with:
          text: |
            ${{ github.event_name == 'issues' && github.event.issue.body || github.event.pull_request.body }}
          api_key: ${{ secrets.GROQ_API_KEY }}
          max_tokens: 500
          
      - name: Add Comment
        uses: actions/github-script@v7
        with:
          script: |
            const eventType = context.eventName === 'issues' ? 'Issue' : 'PR';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ${eventType} 内容总结\n\n${process.env.SUMMARY}`
            })
        env:
          SUMMARY: ${{ steps.summary.outputs.summary }} 